import Nav from "@components/Nav";
import "./globals.css";
import { Inter } from "next/font/google";
import Provider from "@components/Provider";
// import { StyledEngineProvider } from "@mui/material";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="bg-gradient-to-r from-purple-100 via-blue-100 to-pink-200 min-h-screen">
          <Provider>
            <Nav />
            {children}
          </Provider>
        </div>
      </body>
    </html>
  );
}
